version = 1

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x"

  [analyzers.meta]
  test_patterns = ["tests/"]
  exclude_patterns = ["migrations/", "build/"]

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[sinks]]
name = "checks"
enabled = true
