#!/usr/bin/env node
/**
 * Environment Setup Script
 * Creates .env.local from Firebase config for local development
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');

// Firebase project config (from firebase console)
const FIREBASE_CONFIG = {
  projectId: 'anya-bot-1fe76',
  authDomain: 'anya-bot-1fe76.firebaseapp.com',
  storageBucket: 'anya-bot-1fe76.appspot.com',
};

// Bot config
const BOT_CONFIG = {
  botId: '1234247716243112100',
  inviteUrl: 'https://discord.com/api/oauth2/authorize?client_id=1234247716243112100&permissions=8&scope=bot%20applications.commands',
  supportServer: 'https://discord.gg/anya',
};

const envContent = `# Local Development Environment
# Auto-generated by setup-env.js
# Add your API keys below

# Firebase Configuration
VITE_FIREBASE_API_KEY=
VITE_FIREBASE_AUTH_DOMAIN=${FIREBASE_CONFIG.authDomain}
VITE_FIREBASE_PROJECT_ID=${FIREBASE_CONFIG.projectId}
VITE_FIREBASE_STORAGE_BUCKET=${FIREBASE_CONFIG.storageBucket}
VITE_FIREBASE_MESSAGING_SENDER_ID=
VITE_FIREBASE_APP_ID=

# Discord Bot (for local dev stats)
VITE_DISCORD_BOT_TOKEN=
VITE_DISCORD_BOT_ID=${BOT_CONFIG.botId}
VITE_BOT_INVITE_URL=${BOT_CONFIG.inviteUrl}
VITE_SUPPORT_SERVER=${BOT_CONFIG.supportServer}

# Optional APIs
VITE_TENOR_API_KEY=
VITE_GIPHY_API_KEY=
`;

const envPath = path.join(rootDir, '.env.local');

if (fs.existsSync(envPath)) {
  console.log('⚠️  .env.local already exists. Skipping creation.');
  console.log('   Delete it first if you want to regenerate.');
} else {
  fs.writeFileSync(envPath, envContent);
  console.log('✅ Created .env.local');
  console.log('📝 Edit it to add your API keys');
}

console.log('\n📋 Environment files:');
console.log('   .env.local      - Local development (gitignored)');
console.log('   .env.production - Production build');
console.log('   .env.example    - Template for reference');
