/**
 * Setup script to fetch Discord bot token from MongoDB and write to .env
 * 
 * Usage: node scripts/setup-token.js
 * 
 * Reads MongoDB URI from .github/.env and fetches the bot token,
 * then writes it to anya-bot-website/.env
 */

import { MongoClient } from 'mongodb';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Bot configuration (matching Python const.py)
const bot_config = {
  true: {
    prefix: '-',
    token_key: 'Test_Token'
  },
  false: {
    prefix: '.',
    token_key: 'Token'
  }
};

const USE_TEST_BOT = false; // Set to true for test bot

async function main() {
  console.log('🔧 Setting up Discord bot token...\n');

  // Read MongoDB URI from .github/.env
  const githubEnvPath = path.join(__dirname, '../../.github/.env');
  
  if (!fs.existsSync(githubEnvPath)) {
    console.error('❌ .github/.env file not found!');
    console.log('   Please create .github/.env with MONGO_URI=your_mongodb_uri');
    process.exit(1);
  }

  const envContent = fs.readFileSync(githubEnvPath, 'utf-8');
  
  // Parse MONGO_URI
  let mongoUri = null;
  for (const line of envContent.split('\n')) {
    if (line.startsWith('MONGO_URI=') || line.startsWith('MONGODB_URI=')) {
      mongoUri = line.split('=').slice(1).join('=').trim().replace(/['"]/g, '');
      break;
    }
  }

  if (!mongoUri) {
    console.error('❌ MONGO_URI not found in .github/.env!');
    process.exit(1);
  }

  console.log('✅ Found MongoDB URI');

  // Connect to MongoDB
  let client;
  try {
    console.log('📡 Connecting to MongoDB...');
    client = new MongoClient(mongoUri);
    await client.connect();
    console.log('✅ Connected to MongoDB');

    // Get token from Bot.information collection
    const db = client.db('Bot');
    const collection = db.collection('information');
    
    const tokenKey = bot_config[USE_TEST_BOT.toString()].token_key;
    console.log(`🔑 Fetching ${tokenKey} from Bot.information...`);
    
    const tokenDoc = await collection.findOne({ [tokenKey]: { $exists: true } });
    
    if (!tokenDoc || !tokenDoc[tokenKey]) {
      console.error(`❌ ${tokenKey} not found in MongoDB!`);
      process.exit(1);
    }

    const token = tokenDoc[tokenKey];
    console.log('✅ Token retrieved successfully');

    // Write to .env file
    const websiteEnvPath = path.join(__dirname, '../.env');
    
    // Read existing .env or create new
    let existingEnv = '';
    if (fs.existsSync(websiteEnvPath)) {
      existingEnv = fs.readFileSync(websiteEnvPath, 'utf-8');
    }

    // Update or add VITE_DISCORD_BOT_TOKEN
    if (existingEnv.includes('VITE_DISCORD_BOT_TOKEN=')) {
      existingEnv = existingEnv.replace(
        /VITE_DISCORD_BOT_TOKEN=.*/,
        `VITE_DISCORD_BOT_TOKEN=${token}`
      );
    } else {
      existingEnv += `\n# Discord Bot Token (auto-generated by setup-token.js)\nVITE_DISCORD_BOT_TOKEN=${token}\n`;
    }

    fs.writeFileSync(websiteEnvPath, existingEnv.trim() + '\n');
    console.log('✅ Token written to .env');
    
    console.log('\n🎉 Setup complete! Restart your dev server to apply changes.');
    console.log('   Run: npm run dev');

  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  } finally {
    if (client) {
      await client.close();
    }
  }
}

main();
