apiVersion: apps/v1
kind: Deployment
metadata:
  name: anya-bot 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: anya-bot 
  template:
    metadata:
      labels:
        app: anya-bot 
    spec:
      containers:
      - name: anya-bot
        image: anya-devs/anya-bot:latest  
        ports:
        - containerPort: 80  
        envFrom:
        - configMapRef:
            name: anya-bot-config  
